name = "xrynze-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# ==========================================
#  D1 DATABASE BINDING
# ==========================================
[[d1_databases]]
binding = "DB"
database_name = "xrynze-db"
database_id = "536d94bf-46f6-4de3-8539-708c8838ad57"

# BAGIAN [site] SUDAH DIHAPUS
