name = "xrynze-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ==========================================
#  D1 DATABASE BINDING
# ==========================================
[[d1_databases]]
binding = "DB"
database_name = "xrynze-db"
database_id = "isi-id-database-anda-di-sini"

# BAGIAN [site] SUDAH DIHAPUS
